server:
  port: 8080
spring:
  application:
    name: "accounts"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:sqlite:/data/app.db
    driverClassName: org.sqlite.JDBC
    username: ''
    password: ''
  jpa:
    database-platform: com.kurobytes.common.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false # SECURITY: Disable SQL logging in production
management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "metrics"] # SECURITY: Only expose safe endpoints
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: false # SECURITY: Disable shutdown endpoint
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}


info:
  app:
    name: "accounts"
    description: "Kuro Bank Accounts Application"
    version: "1.0.0"

logging:
  level:
    com:
      kurobytes:
        accounts: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 500
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      ignoreExceptions:
        - java.lang.NullPointerException
      retryExceptions:
        - java.util.concurrent.TimeoutException

resilience4j.ratelimiter:
  configs:
    default:
      timeoutDuration: 1000
      limitRefreshPeriod: 5000
      limitForPeriod: 1
